language: java

sudo: false

before_cache:
    - sudo chown -R travis:travis $HOME/.m2

cache:
  directories:
    - ${HOME}/.m2

matrix:
  include:
    # All tests
    - os: linux
      sudo: false
      jdk: "openjdk8"
      dist: xenial
      # env: ENV=...

script:
  - ./gradlew test

after_success:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"

after_failure:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
